# Generated by Django 5.2.1 on 2025-05-11 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_fileupload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='pub_date',
        ),
    ]
